.PHONY: just
just:
	./macas main.as
	./macas printf.as
	./macas	toint.as
	./macas scan.as
	./macas scanf.as
	./macas	memcopy.as
	./maclk just.mac main.maco printf.maco toint.maco scan.maco scanf.maco memcopy.maco

.PHONY: clean
clean:
	rm -rf *.mac
	rm -rf *.maco
	clear
